/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.harshdev.goosbook

class Main {
    static final String SNIPER_STATUS_NAME = ""
    static final String TOP_WINDOW_NAME = ""

    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new Main().greeting
    }
}
