/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.harshdev.goosbook.auctionsniper

import org.harshdev.goosbook.auctionsniper.ui.MainWindow
import org.harshdev.goosbook.auctionsniper.xmpp.AuctionHouse

import javax.swing.*

class Main {

    private static final int ARGS_HOSTNAME = 0
    private static final int ARGS_USERNAME = 1
    private static final int ARGS_PASSWORD = 2
    static final String MAIN_WINDOW_NAME = ""
    private SniperPortfolio portfolio

    private static Main main

    private MainWindow ui
    private AuctionHouse auctionHouse


    Main() throws Exception {
        portfolio = new SniperPortfolio()
    }

    static void main(String[] args) {
        main = new Main();
        main.auctionHouse = new AuctionHouse(args[ARGS_USERNAME], args[ARGS_PASSWORD], args[ARGS_HOSTNAME])
        main.auctionHouse.connect()
        main.startUserInterface()
    }


    static void stop() {
        if (Objects.nonNull(main.auctionHouse)) {
            main.auctionHouse.stop()
        }

        main.ui.dispose()
    }


    private void startUserInterface() throws Exception {
        SniperLauncher launcher = new SniperLauncher(auctionHouse, portfolio, (Runnable runnable) -> new Thread(runnable).start())
        SwingUtilities.invokeAndWait(() -> {
            ui = new MainWindow(portfolio)
            ui.addUserEventListener(launcher)
        })




    }
}
